# Используем официальный образ Ubuntu в качестве базового
FROM ubuntu:22.04

# Устанавливаем переменную окружения для предотвращения интерактивных запросов при установке пакетов
ENV DEBIAN_FRONTEND=noninteractive
ENV PIP_BREAK_SYSTEM_PACKAGES 1

# Обновляем пакеты и устанавливаем необходимые зависимости
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    x11vnc \
    xvfb \
    fluxbox 

RUN apt-get install -y python3-tk python3-dev xclip dbus-x11 xdotool gnome-screenshot
# Устанавливаем пароль для VNC через переменную окружения
# ENV VNC_PASSWORD=Doszhan89!
COPY passwd /root/.vnc/


COPY ./app/requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \ 
    pip install --no-cache-dir -r requirements.txt

RUN apt-get install -y curl x11-xserver-utils

# Создаем директорию для приложения
WORKDIR /app/

# Копируем основной Python-скрипт
COPY app/ ./
# COPY main.py .


# Копируем скрипт запуска
COPY sh/entrypoint.sh /sh/entrypoint.sh
RUN chmod +x /sh/entrypoint.sh

# Открываем порты для VNC
EXPOSE 5900
EXPOSE 50051

# Устанавливаем точку входа
ENTRYPOINT ["sh", "/sh/entrypoint.sh" ]
