version: '3.9'

volumes:
  gz_redis:
    external: true
    name: gz_redis
  gz_rabbitmq:
    external: true
    name: gz_rabbitmq

services:
  dashboard:
    build: dashboard/.
    entrypoint: ["sh", "./sh/app.sh"]      
    restart: always
    network_mode: host
    env_file:
      - env/dashboard.env
    volumes:
      - ./dashboard/app:/dashboard/
    depends_on:
      - rabbitmq
      
  beat_dashboard:
    build: dashboard/.
    entrypoint: ["sh", "./sh/beat.sh"]  
    restart: always
    network_mode: host
    env_file:
      - env/dashboard.env    
    volumes:
      - ./dashboard/app:/dashboard/
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3.12.13"
    restart: always
    ports:
      - "5672:5672"    
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq_user"
      RABBITMQ_DEFAULT_PASS: "rabbitmq_pass"
      TZ: Asia/Almaty
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit consumer_timeout 2592000000
    volumes:
      - gz_rabbitmq:/var/lib/rabbitmq      

  flower:
    image: mher/flower:2.0
    command: [ "celery", "flower", "--url-prefix=flower_backend" ]
    restart: always
    ports:
      - 5554:5555    
    environment:
      - CELERY_ENABLE_UTC=True
      - CELERY_BROKER=amqp://rabbitmq_user:rabbitmq_pass@rabbitmq
      - FLOWER_BASIC_AUTH=pk_flower:flower_pass
    logging:
      driver: "none"
    depends_on:
      - rabbitmq
    mem_limit: 500M
    mem_reservation: 100m    
    
  # redis:
  #   image: "redis:7.2.5"
  #   restart: always
  #   ports:
  #     - "6379:6379"    
  #   volumes:
  #     - gz_redis:/data         