version: '3.9'

services:
  redis:
    image: redis:7.2.2
    restart: always
    ports:
      - 6379:6379

  ncanode:
    image: nurdinkz/ncanode:2.3.1
    restart: always
    logging:
      driver: "none"
    ports:
      - "14579:14579"
