version: '3.9'

services:
  rabbitmq:
    image: "rabbitmq:3.12.13"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq_user"
      RABBITMQ_DEFAULT_PASS: "rabbitmq_pass"
      TZ: Asia/Almaty
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit consumer_timeout 2592000000
    volumes:
      - "./rabbitmq:/var/lib/rabbitmq"      
    ports:
      - "5672:5672"

  flower:
    image: mher/flower:2.0
    command: [ "celery", "flower", "--url-prefix=flower_backend" ]
    restart: always
    environment:
      - CELERY_ENABLE_UTC=True
      - CELERY_BROKER=amqp://rabbitmq_user:rabbitmq_pass@rabbitmq
      - FLOWER_BASIC_AUTH=pk_flower:flower_pass
    logging:
      driver: "none"
    ports:
      - 5554:5555
    depends_on:
      - rabbitmq
    mem_limit: 500M
    mem_reservation: 100m    
    