version: '3.9'

services:
  rabbitmq:
    image: "rabbitmq:3.12.13"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq_user"
      RABBITMQ_DEFAULT_PASS: "rabbitmq_pass"
      TZ: Asia/Almaty
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit consumer_timeout 2592000000
    volumes:
      - "./rabbitmq:/var/lib/rabbitmq"      
    ports:
      - "5672:5672"
