# Generated by Django 5.0.2 on 2024-02-22 11:47

import dashboard.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin_bin', models.CharField(default='141140001428', max_length=255, unique=True, verbose_name='ИИН/БИН участника')),
                ('name', models.CharField(default="ТОО 'Сивер плюс'", max_length=255, verbose_name='Наименование участника')),
                ('eds_auth', models.FileField(upload_to=dashboard.models.eds_directory_path, verbose_name='ЭЦП для авторизации')),
                ('eds_gos', models.FileField(upload_to=dashboard.models.eds_directory_path, verbose_name='ЭЦП для подписания')),
                ('eds_pass', models.CharField(max_length=255, verbose_name='Пароль от ЭЦП')),
                ('goszakup_pass', models.CharField(max_length=255, verbose_name='Пароль на сайте Госзакупа')),
                ('subject_address', models.CharField(default='050061', help_text='Необходимо ввести индекс, который зарегистрирован на сайте', max_length=255, verbose_name='Индекс')),
                ('iik', models.CharField(default='KZ5696502F0017154550', help_text='Необходимо ввести счет, который зарегистрирован на сайте', max_length=255, verbose_name='Счет для оплаты')),
                ('contact_phone', models.CharField(default='7014333488', help_text='Необходимо ввести номер, который зарегистрирован на сайте, вводить без 8 или +7. Пример: 7014333488', max_length=255, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce_number', models.CharField(max_length=256, unique=True, verbose_name='Номер объявления')),
                ('announce_name', models.TextField(blank=True, null=True, verbose_name='Название конкурса')),
                ('status', models.CharField(choices=[('checking', 'Проверка объявления'), ('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('success', 'Завершено успешно!'), ('error', 'Завершено с ошибкой!')], default='checking', max_length=256, verbose_name='Статус')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Запланированное время старта')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время старта')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Продолжительность выполнения')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Описание ошибки')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.participant', verbose_name='Участник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'task',
            },
        ),
    ]
