# Generated by Django 5.0.7 on 2024-09-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_participant_eds_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='announce_number',
            field=models.CharField(max_length=256, verbose_name='Номер объявления'),
        ),
    ]
