# Generated by Django 5.0.7 on 2024-09-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_task_announce_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('checking', 'Проверка объявления'), ('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('success', 'Успешно!'), ('error', 'Ошибка!')], default='checking', max_length=256, verbose_name='Статус'),
        ),
    ]
