# Используем официальный образ Ubuntu в качестве базового
FROM ubuntu:22.04

# Установка переменных окружения
ENV DEBIAN_FRONTEND=noninteractive
ENV PIP_BREAK_SYSTEM_PACKAGES=1

# Установка необходимых пакетов
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    x11vnc \
    xvfb \
    supervisor \
    python3-tk \
    python3-dev \
    xclip \
    dbus-x11 \
    xdotool \
    gnome-screenshot \
    curl \
    vim \
    xxd \
    libnss3-tools \
    xdg-utils \
    bsdmainutils \
    iproute2 

# Создание пользователя 'asus' с домашней директорией и добавление в группу 'sudo' (опционально)
RUN useradd -m -s /bin/bash asus

# Копирование файла пароля VNC в домашнюю директорию 'asus'
COPY passwd /home/asus/.vnc/passwd

# Изменение владельца файла пароля VNC на пользователя 'asus'
RUN chown asus:asus /home/asus/.vnc/passwd

# Установка прав на выполнение для файла пароля VNC
RUN chmod 600 /home/asus/.vnc/passwd

# Установка рабочей директории
WORKDIR /app/

# Копирование файла зависимостей Python и установка их от имени 'asus'
COPY --chown=asus:asus ./app/requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -r /app/requirements.txt

# Копирование основного кода приложения от имени 'asus'
COPY --chown=asus:asus app/ /app/

# Копирование скрипта запуска и установка прав на выполнение
COPY --chown=asus:asus sh/entrypoint.sh /sh/entrypoint.sh
RUN chmod +x /sh/entrypoint.sh

# Копирование скриптов NCALayer и установка прав на выполнение
COPY --chown=asus:asus ncalayer/ /ncalayer/
RUN chmod +x /ncalayer/ncalayer.sh

# Создание необходимой директории и изменение владельца на 'asus'
RUN mkdir -p /home/asus/Programs && chown -R asus:asus /home/asus/Programs

# Копирование конфигурационного файла supervisord и изменение владельца
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
RUN chown asus:asus /etc/supervisor/conf.d/supervisord.conf
# Создаем директорию для логов и устанавливаем права
RUN mkdir -p /home/asus/logs && chmod -R 777 /home/asus/logs
RUN chown asus:asus /home/asus/logs

RUN apt install nginx -y
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/certs /etc/nginx/certs
RUN chown -R asus:asus /etc/nginx/certs/
RUN chown -R asus:asus /etc/nginx/
RUN chown -R asus:asus /var/log/nginx/
RUN chown -R asus:asus /var/lib/nginx/
RUN chmod 644 /etc/nginx/certs/selfsigned.crt
RUN chmod 600 /etc/nginx/certs/selfsigned.key
RUN mkdir -p /var/run/nginx && chown -R asus:asus /var/run/nginx

# Переключение на пользователя 'asus'
USER asus

# Открытие порта VNC
EXPOSE 5900

# Установка точки входа на supervisord через entrypoint.sh
ENTRYPOINT ["sh", "/sh/entrypoint.sh"]
