# Generated by Django 5.0.2 on 2024-02-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='announce_number',
            field=models.CharField(default='', max_length=256, verbose_name='Номер объявления'),
            preserve_default=False,
        ),
    ]
