# Generated by Django 5.0.2 on 2024-02-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_task_announce_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='eds_gos',
            field=models.FileField(default='', upload_to='eds/', verbose_name='ЭЦП для подписания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='eds_auth',
            field=models.FileField(upload_to='eds/', verbose_name='ЭЦП для авторизации'),
        ),
    ]
