# Generated by Django 5.0.2 on 2024-02-21 15:23

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_participant_eds_gos_alter_participant_eds_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='eds_auth',
            field=models.FileField(upload_to=dashboard.models.eds_directory_path, verbose_name='ЭЦП для авторизации'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='eds_gos',
            field=models.FileField(upload_to=dashboard.models.eds_directory_path, verbose_name='ЭЦП для подписания'),
        ),
    ]
