# Generated by Django 5.0.2 on 2024-02-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_participant_eds_auth_alter_participant_eds_gos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='announce_number',
            field=models.CharField(max_length=256, unique=True, verbose_name='Номер объявления'),
        ),
    ]
