# Generated by Django 5.0.2 on 2024-02-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_task_announce_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('checking', 'Проверка объявления'), ('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('success', 'Завершено успешно!'), ('error', 'Завершено с ошибкой!')], default='checking', max_length=256, verbose_name='Статус'),
        ),
    ]
