# Generated by Django 5.0.2 on 2024-02-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='company',
            new_name='participant',
        ),
    ]
