# Generated by Django 5.0.2 on 2024-02-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_company_task_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней проверки'),
        ),
    ]
