# Generated by Django 5.0.2 on 2024-02-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_task_last_check_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='announce_name',
            field=models.TextField(blank=True, null=True, verbose_name='Название конкурса'),
        ),
    ]
