# Generated by Django 5.0.2 on 2024-02-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_task_announce_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней ошибки'),
        ),
    ]
