# Generated by Django 5.0.2 on 2024-02-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_task_last_check_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Продолжительность выполнения'),
        ),
    ]
