# Generated by Django 5.0.2 on 2024-02-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_task_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_check_time',
        ),
    ]
